Chat/Models/SearchByUIdViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Messenger.Models
{
    public class SearchByUIdViewModel
    {
        public int UId { get; set; }
    }
}

Chat/Controllers/SearchByUIdController.cs
using Messenger.Contexts;
using Messenger.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Messenger.Controllers
{
    public class SearchByUIdController : Controller
    {
        private readonly MessengerDbContext dbContext;

        public SearchByUIdController(MessengerDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(SearchByUIdViewModel model)
        {
            var user = dbContext.Users.FirstOrDefault(x => x.UId == model.UId);

            if(user is null)
            {
                return NotFound();
            }

            return RedirectToAction("Invite", "Invitation", new { id = user.Id });
        }
    }
}

Chat/Views/SearchByUId/Index.cshtml
@model Messenger.Models.SearchByUIdViewModel

<h2>Searcth by UId</h2>

<form asp-action="Index" asp-controller="SearchByUId">
    <div>
        <div class="form-group">
            <label asp-for="UId">Enter user UId:</label>
            <input type="text" asp-for="UId" />
            <span asp-validation-for="UId" />
        </div>
        <div class="validation" asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <input type="submit" value="Add" class="btn btn-outline-dark" />
        </div>
    </div>
</form>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}