Chat/Controllers/SettingsController.cs
using Messenger.Contexts;
using Messenger.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Messenger.Controllers
{
    public class SettingsController : Controller
    {
        private readonly MessengerDbContext dbContext;

        public SettingsController(MessengerDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Index() 
        {
            var user = dbContext.Users.FirstOrDefault(x => x.Email == User.Identity.Name);

            return View(new SettingsViewModel
            {
                UId = user.UId,
                IsVisible = user.IsVisible
            });
        }

        [HttpPost]
        public IActionResult Index(SettingsViewModel model)
        {
            if (model.NewUserName != null)
            {
                dbContext.Users.FirstOrDefault(x => x.Email == User.Identity.Name).UserName = model.NewUserName;
            }

            if (model.NewPassword != null)
            {
                dbContext.Users.FirstOrDefault(x => x.Email == User.Identity.Name).Password = model.NewPassword;
            }

            if(model.IsVisible != dbContext.Users.FirstOrDefault(x => x.Email == User.Identity.Name).IsVisible)
            {
                dbContext.Users.FirstOrDefault(x => x.Email == User.Identity.Name).IsVisible = model.IsVisible;
            }

            dbContext.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

Chat/Controllers/UserController.cs
using Messenger.Contexts;
using Messenger.CoreModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Messenger.Controllers
{
    public class UserController : Controller
    {
        private readonly MessengerDbContext dbContext;

        public UserController(MessengerDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var result = new List<User>();
            if (User.Identity.IsAuthenticated)
            {
                var users = dbContext.Users.ToList();
                var user = dbContext.Users.FirstOrDefault(user => user.Email == User.Identity.Name);
                var userFriends = dbContext.UserFriends
                    .Where(x => (x.UserId == user.Id || x.FriendId == user.Id))
                    .ToList();

                for (int j = 0; j < users.Count; j++)
                {
                    if (user.Id == users[j].Id)
                    {
                        continue;
                    }

                    if (!userFriends.Any(x => x.FriendId == users[j].Id || x.UserId == users[j].Id) 
                        && users[j].IsVisible)
                    {
                        result.Add(users[j]);
                    }
                }
            }

            return View(result);
        }

        [HttpPost]
        public IActionResult Index(User user)
        {
            return View(dbContext.Users.FirstOrDefault(x => x.UId == user.UId));
        }
    }
}

Chat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Chat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Chat</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Friend" asp-action="Index">Friends</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Settings" asp-action="Index">Settings</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Chat - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>